Fixed ``urllib3.utils.create_urllib3_context()`` when missing default context.
